name: Deploy site

on:
  push:
    branches:
      - master

jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./EldoMvideo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eldomvideo:latest

  run-docker:
    needs: push-docker
    runs-on: self-hosted
    steps:
      - name: Rm image
        run: sudo docker rmi -f strhzy/eldomvideo
      
      - name: Pull image
        run: sudo docker pull strhzy/eldomvideo
        
      - name: Get docker-compose
        run: sudo curl -OJ https://raw.githubusercontent.com/strhzy/EldoMvideo/refs/heads/master/EldoMvideo/compose.yaml
        
      - name: Run docker-compose
        run: sudo docker-compose up -d
